"""Faithful Python port of the quote-visibility projection math from
packages/shared/src/hubspot/dealRollups.ts (pure, no I/O).

Shapes mirror the TS interfaces as plain dicts so the parity fixture
(tests/fixtures/rollup_parity.json, generated by parity/gen.mjs from the REAL
TS implementation) can drive both sides with identical inputs. Keep 1:1 with
the TS file — behavior changes belong there first.
"""

from __future__ import annotations

import math
from datetime import datetime, timedelta, timezone

DAY_MS = 86_400_000
PIPELINE_FRESH_DAYS = 180

PROP_YTD = "ytd_won_deals"
PROP_PRIOR_YTD = "ytd_prior_year_won_deals"
PROP_PRIOR_YEAR = "prior_year_won_deals"
PROP_YTD_LOST = "ytd_lost_deals"
PROP_PIPELINE = "future_pipeline_value"
PROP_CREATION = "future_creation_value"
PROP_PROJECTED = "projected_sales_quote_visibility"

ALL_PROPS = [
    PROP_YTD, PROP_PRIOR_YTD, PROP_PRIOR_YEAR, PROP_YTD_LOST,
    PROP_PIPELINE, PROP_CREATION, PROP_PROJECTED,
]

PRIMARY_TYPE_ID = 5


def date_utc(year: int, month0: int, day: int) -> float:
    """JS Date.UTC(year, month0, day) in ms — including out-of-range rollover
    (month0 12 → next Jan; day 29 in non-leap Feb → Mar 1)."""
    y = year + month0 // 12
    m = month0 % 12
    base = datetime(y, m + 1, 1, tzinfo=timezone.utc) + timedelta(days=day - 1)
    return base.timestamp() * 1000


def round2(n: float) -> float:
    """JS Math.round(n*100)/100 — half away from zero toward +inf."""
    return math.floor(n * 100 + 0.5) / 100


def _num(v) -> float | None:
    if v is None or v == "":
        return None
    try:
        n = float(v)
    except (TypeError, ValueError):
        return None
    return n if math.isfinite(n) else None


def lost_value(d: dict) -> float | None:
    v = _num(d.get("maxAmount"))
    return v if v is not None else _num(d.get("amount"))


def deal_rollup_windows(now_ms: float) -> dict:
    d = datetime.fromtimestamp(now_ms / 1000, tz=timezone.utc)
    y = d.year
    jan_current = date_utc(y, 0, 1)
    return {
        "nowMs": now_ms,
        "ytdStartMs": jan_current,
        "priorStartMs": date_utc(y - 1, 0, 1),
        "priorYtdEndMs": date_utc(y - 1, d.month - 1, d.day) + DAY_MS,
        "priorYearEndMs": jan_current,
        "pipelineCreateCeilingMs": date_utc(y, 10, 1),
        "pipelineFreshFloorMs": now_ms - PIPELINE_FRESH_DAYS * DAY_MS,
    }


def pick_rollup_company_id(assocs: list[dict]) -> str | None:
    primary = list(dict.fromkeys(
        a["companyId"] for a in assocs if PRIMARY_TYPE_ID in a.get("typeIds", [])
    ))
    if len(primary) == 1:
        return primary[0]
    if len(primary) > 1:
        return None
    distinct = list(dict.fromkeys(a["companyId"] for a in assocs))
    return distinct[0] if len(distinct) == 1 else None


def _same_utc_day(a: float | None, b: float | None) -> bool:
    return a is not None and b is not None and math.floor(a / DAY_MS) == math.floor(b / DAY_MS)


def adjusted_value_hit_rate(won: list[dict], lost: list[dict], from_ms: float, to_ms: float) -> float | None:
    won_sum = 0.0
    lost_sum = 0.0
    for d in won:
        t = d.get("closedateMs")
        if t is None or t < from_ms or t > to_ms:
            continue
        if _same_utc_day(t, d.get("createdateMs")):
            continue
        won_sum += _num(d.get("amount")) or 0
    for d in lost:
        t = d.get("closedateMs")
        if t is None or t < from_ms or t > to_ms:
            continue
        if _same_utc_day(t, d.get("createdateMs")):
            continue
        lost_sum += lost_value(d) or 0
    denom = won_sum + lost_sum
    return won_sum / denom if denom > 0 else None


def pipeline_in_year_yield(cohort: list[dict], snapshot_ms: float, year_end_ms: float) -> dict:
    fresh_floor = snapshot_ms - PIPELINE_FRESH_DAYS * DAY_MS
    base = 0.0
    wins = 0.0
    eventual = 0.0
    for d in cohort:
        c = d.get("createdateMs")
        if c is None or c < fresh_floor or c >= snapshot_ms:
            continue
        cl = d.get("closedateMs")
        if cl is not None and cl < snapshot_ms:
            continue
        if d.get("preQualified"):
            continue
        base += lost_value(d) or 0
        if d.get("won") and cl is not None:
            eventual += _num(d.get("amount")) or 0
            if cl < year_end_ms:
                wins += _num(d.get("amount")) or 0
    return {
        "base": base,
        "wins": wins,
        "eventualWins": eventual,
        "yield": wins / base if base > 0 else None,
        "timing": wins / eventual if eventual > 0 else None,
    }


def creation_seasonality(deals: list[dict], year: int) -> dict:
    wins_by_month = [0.0] * 12
    creation_by_month = [0.0] * 12
    year_start = date_utc(year, 0, 1)
    year_end = date_utc(year + 1, 0, 1)
    for d in deals:
        c = d.get("createdateMs")
        if c is None or c < year_start or c >= year_end:
            continue
        m = datetime.fromtimestamp(c / 1000, tz=timezone.utc).month - 1
        creation_by_month[m] += lost_value(d) or 0
        cl = d.get("closedateMs")
        if d.get("won") and cl is not None and cl < year_end:
            wins_by_month[m] += _num(d.get("amount")) or 0
    return {"winsByCreationMonth": wins_by_month, "creationValueByMonth": creation_by_month}


def creation_value_in_window(deals: list[dict], start_ms: float, end_ms: float) -> float:
    total = 0.0
    for d in deals:
        c = d.get("createdateMs")
        if c is None or c < start_ms or c >= end_ms:
            continue
        total += lost_value(d) or 0
    return total


def expected_future_creation_wins(seasonality: dict, now_ms: float, yoy_factor: float) -> float:
    d = datetime.fromtimestamp(now_ms / 1000, tz=timezone.utc)
    m = d.month - 1
    days_in_month = (
        datetime.fromtimestamp(date_utc(d.year, m + 1, 0) / 1000, tz=timezone.utc).day
    )
    frac_remaining = (days_in_month - d.day) / days_in_month
    total = seasonality["winsByCreationMonth"][m] * frac_remaining
    for k in range(m + 1, 12):
        total += seasonality["winsByCreationMonth"][k]
    return total * yoy_factor


def aggregate_extended_rollups(input_: dict, w: dict, rates: dict) -> dict[str, dict[str, float]]:
    out: dict[str, dict[str, float]] = {}

    def props(company_id: str) -> dict[str, float]:
        if company_id not in out:
            out[company_id] = {p: 0.0 for p in ALL_PROPS}
        return out[company_id]

    for d in input_.get("won", []):
        t = d.get("closedateMs")
        if t is None:
            continue
        amt = _num(d.get("amount"))
        if amt is None:
            continue
        p = props(d["companyId"])
        if w["ytdStartMs"] <= t <= w["nowMs"]:
            p[PROP_YTD] += amt
        if w["priorStartMs"] <= t < w["priorYtdEndMs"]:
            p[PROP_PRIOR_YTD] += amt
        if w["priorStartMs"] <= t < w["priorYearEndMs"]:
            p[PROP_PRIOR_YEAR] += amt
    for d in input_.get("lost", []):
        t = d.get("closedateMs")
        if t is None or t < w["ytdStartMs"] or t > w["nowMs"]:
            continue
        v = lost_value(d)
        if v is None:
            continue
        props(d["companyId"])[PROP_YTD_LOST] += v
    for d in input_.get("open", []):
        c = d.get("createdateMs")
        if c is None or c < w["pipelineFreshFloorMs"] or c >= w["pipelineCreateCeilingMs"]:
            continue
        amt = _num(d.get("amount"))
        if amt is None:
            continue
        props(d["companyId"])[PROP_PIPELINE] += amt * (rates.get("pipelineYield") or 0)
    for company_id, share in (input_.get("creationByCompany") or {}).items():
        if share > 0:
            props(company_id)[PROP_CREATION] += share
    for p in out.values():
        vr = rates.get("visibilityRate")
        p[PROP_PROJECTED] = (p[PROP_YTD] + p[PROP_PIPELINE] + p[PROP_CREATION]) / vr if vr else 0.0
        for k in list(p):
            p[k] = round2(p[k])
    return out
