"""Parity: the Python port must reproduce the TS dealRollups math exactly.

Fixture generated by parity/gen.ts from the REAL packages/shared
implementation (see its header for the regen command).
"""

import json
import math
from pathlib import Path

import pytest

from wac_forecast.baselines import quote_visibility as qv

FIXTURE = json.loads((Path(__file__).parent / "fixtures" / "rollup_parity.json").read_text())


def close(a, b, tol=1e-9):
    if a is None or b is None:
        return a is None and b is None
    return math.isclose(a, b, rel_tol=0, abs_tol=tol) or math.isclose(a, b, rel_tol=1e-12)


def test_windows():
    w = qv.deal_rollup_windows(FIXTURE["nowMs"])
    for k, v in FIXTURE["windows"].items():
        assert w[k] == v, k


def test_leap_windows():
    w = qv.deal_rollup_windows(FIXTURE["leapWindows"]["nowMs"])
    for k, v in FIXTURE["leapWindows"].items():
        assert w[k] == v, k


def test_pipeline_in_year_yield():
    got = qv.pipeline_in_year_yield(
        FIXTURE["cohort"], FIXTURE["snapshotMs"], FIXTURE["windows"]["priorYearEndMs"]
    )
    for k in ("base", "wins", "eventualWins", "yield", "timing"):
        assert close(got[k], FIXTURE["yieldRes"][k]), k


def test_hit_rate():
    won = [d for d in FIXTURE["cohort"] if d["won"] and d["closedateMs"] is not None]
    lost = [d for d in FIXTURE["cohort"] if not d["won"] and d["closedateMs"] is not None]
    got = qv.adjusted_value_hit_rate(
        won, lost, FIXTURE["nowMs"] - 365 * qv.DAY_MS, FIXTURE["nowMs"]
    )
    assert close(got, FIXTURE["hitRate"])


def test_seasonality_and_future_wins():
    got = qv.creation_seasonality(FIXTURE["cohort"], 2025)
    for k in ("winsByCreationMonth", "creationValueByMonth"):
        assert all(close(a, b) for a, b in zip(got[k], FIXTURE["seasonality"][k])), k
    fw = qv.expected_future_creation_wins(got, FIXTURE["nowMs"], FIXTURE["yoyFactor"])
    assert close(fw, FIXTURE["futureWins"])


def test_creation_value_in_window():
    got = qv.creation_value_in_window(
        FIXTURE["cohort"], FIXTURE["windows"]["ytdStartMs"], FIXTURE["nowMs"]
    )
    assert close(got, FIXTURE["creationWindowValue"])


def test_aggregate_extended_rollups():
    cohort = FIXTURE["cohort"]
    won = [d for d in cohort if d["won"] and d["closedateMs"] is not None]
    lost = [d for d in cohort if not d["won"] and d["closedateMs"] is not None]
    open_ = [d for d in cohort if d["closedateMs"] is None]
    got = qv.aggregate_extended_rollups(
        {
            "won": won,
            "lost": lost,
            "open": open_,
            "creationByCompany": FIXTURE["creationByCompany"],
        },
        FIXTURE["windows"],
        {"pipelineYield": FIXTURE["yieldRes"]["yield"], "visibilityRate": FIXTURE["visibilityRate"]},
    )
    expected = FIXTURE["aggregated"]
    assert set(got) == set(expected)
    for company, props in expected.items():
        for name, val in props.items():
            assert close(got[company][name], val, tol=0.01), f"{company}.{name}"


@pytest.mark.parametrize("case", FIXTURE["assocCases"])
def test_pick_rollup_company_id(case):
    assert qv.pick_rollup_company_id(case["assocs"]) == case["expected"]
