-- =============================================================================
-- Descriptions — WAC Lighting + WAC Architectural upload slots.
--
-- Adds four file slots to the Descriptions feature (0072):
--   wac_master     — WAC Lighting master list (brand "WAC Lighting",
--                    collection "Limited")
--   wacarch_master — WAC Architectural master list (brand "WAC Architectural",
--                    collection "Core")
--   wac_pptx / wacarch_pptx — their paired introductions decks (enrichment,
--                    same lane as dweled_pptx)
--
-- The slot CHECK constraints from 0072 were created inline (auto-named), so
-- this migration drops whatever CHECK mentions the slot column on each table
-- and re-adds a named 10-slot (5-slot for desc_enrichment) constraint.
-- Idempotent: re-running drops the named constraint and re-adds it.
--
-- Also seeds the "WAC Architectural · Core" voice profile — text mirrors
-- packages/shared/src/descriptions/voiceDefaults.ts EXACTLY
-- (voiceDefaults.test.ts enforces the sync). WAC Lighting · Limited was
-- already seeded in 0072.
--
-- Plus desc_content.name_override: an editor's corrected product name
-- (placeholder Sigfor/2028 names like "41QF0303"). Lives on desc_content —
-- exactly like title_override — so the correction survives re-imports.
-- Display name = name_override ?? imported name.
-- =============================================================================

alter table public.desc_content
  add column if not exists name_override text;

-- ---------------------------------------------------------------------------
-- Drop every CHECK constraint that references the slot column (names were
-- auto-generated by the inline checks in 0072, so match by definition).
-- ---------------------------------------------------------------------------
do $$
declare
  r record;
begin
  for r in
    select c.conname, c.conrelid::regclass::text as tbl
    from pg_constraint c
    where c.contype = 'c'
      and c.conrelid in (
        'public.desc_imports'::regclass,
        'public.desc_products'::regclass,
        'public.desc_product_images'::regclass,
        'public.desc_content'::regclass,
        'public.desc_enrichment'::regclass
      )
      and pg_get_constraintdef(c.oid) like '%slot%'
  loop
    execute format('alter table %s drop constraint %I', r.tbl, r.conname);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Re-add the slot checks with the full 10-slot list (desc_enrichment holds
-- supplement slots only).
-- ---------------------------------------------------------------------------
alter table public.desc_imports add constraint desc_imports_slot_check
  check (slot in
    ('dweled_master','wac_master','wacarch_master','mf_master','schonbek_master',
     'dweled_pptx','wac_pptx','wacarch_pptx','mf_pdf','schonbek_pdf'));

alter table public.desc_products add constraint desc_products_slot_check
  check (slot in
    ('dweled_master','wac_master','wacarch_master','mf_master','schonbek_master',
     'dweled_pptx','wac_pptx','wacarch_pptx','mf_pdf','schonbek_pdf'));

alter table public.desc_product_images add constraint desc_product_images_slot_check
  check (slot in
    ('dweled_master','wac_master','wacarch_master','mf_master','schonbek_master',
     'dweled_pptx','wac_pptx','wacarch_pptx','mf_pdf','schonbek_pdf'));

alter table public.desc_content add constraint desc_content_slot_check
  check (slot in
    ('dweled_master','wac_master','wacarch_master','mf_master','schonbek_master',
     'dweled_pptx','wac_pptx','wacarch_pptx','mf_pdf','schonbek_pdf'));

alter table public.desc_enrichment add constraint desc_enrichment_slot_check
  check (slot in
    ('dweled_pptx','wac_pptx','wacarch_pptx','mf_pdf','schonbek_pdf'));

-- ---------------------------------------------------------------------------
-- Voice profile seed — WAC Architectural · Core. Text mirrors
-- packages/shared/src/descriptions/voiceDefaults.ts EXACTLY.
-- ---------------------------------------------------------------------------
insert into public.desc_voice_profiles (brand, collection, prompt, voice_guidance)
values
  ('WAC Architectural', 'Core', $prompt$Write 75-word marketing catalog copy for this product, based on the product fact sheet provided.

Describe the design details a shopper can see, and weave in the specific product facts supplied (LED color temperature, finishes, sizes, materials, features). Never invent specifications; only use the attributes provided.

Plain text only: no markdown, no headings, no exclamation marks, no hype words. No em dashes. When referring to the company, always write WAC Group, never WAC alone.

HARD RULE: capture the same kinds of information for every product, but never the same shape: vary the opening, sentence order, and rhythm from product to product. Do not start two descriptions the same way.$prompt$,
   $voice$Seeded default, refine me. WAC Architectural is precision architectural lighting for designed spaces. Performance-minded and understated: speak to optics, light quality, and how the fixture integrates with the architecture. Clean, specification-aware sentences that still convey design intent.$voice$)
on conflict (brand, collection) do nothing;
